name: Bass

on:
  push:
    paths:
      - 'bass/**'
      - '.github/workflows/bass.yml'

jobs:
  publish:
    name: Publish nuget package
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: bass

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 9.0.x
          source-url: https://nuget.pkg.github.com/dmirmilshteyn/index.json
      - name: Pack
        run: nuget pack -OutputDirectory ${{ github.workspace }}/bin ./bass.nuspec
      - name: Publish packages
        run: dotnet nuget push ${{ github.workspace }}/bin/*.nupkg --skip-duplicate --api-key ${{ github.token }} --source https://nuget.pkg.github.com/dmirmilshteyn/