name: bassflac

on:
  push:
    paths:
      - 'bassflac/**'
      - '.github/workflows/bassflac.yml'

jobs:
  publish:
    name: Publish nuget package
    runs-on: ubuntu-22.04 # Bug with nuget action forces use of this version

    defaults:
      run:
        working-directory: bassflac

    steps:
      - uses: actions/checkout@v2
      - uses: nuget/setup-nuget@v2
        with:
          nuget-version: 'latest'
      - name: Pack
        run: nuget pack -OutputDirectory ${{ github.workspace }}/bin ./bassflac.nuspec
      - name: Publish
        run: nuget push ${{ github.workspace }}/bin/*.nupkg -ApiKey ${{ secrets.CI_PACKAGES_PAT }} -Source https://api.nuget.org/v3/index.json -NonInteractive